import {
  DEFAULT_ASSISTANT_LOCALE,
  normalizeAssistantLocale,
  type AssistantLocale,
} from "@/lib/assistant/locales";

export interface AssistantUICopy {
  title: string;
  subtitle: string;
  companionLabel: string;
  greeting: string;
  privateAccess: string;
  notifications: string;
  contactReplies: string;
  siteRules: string;
  emptyState: string;
  handoffPrompt: string;
  openContactDraft: string;
  cancel: string;
  privacyNote: string;
  inputPlaceholder: string;
  inputLabel: string;
  sendLabel: string;
  closeLabel: string;
  askDock: string;
  hideDock: string;
  contactHandoffTitle: string;
  unknownAnswer: string;
  emptyQuestionTitle: string;
  emptyQuestionAnswer: string;
  signIn: string;
  authRequiredAnswer: string;
  unreadNotification: (count: number) => string;
  openPath: (path: string) => string;
  sendToContact: string;
}

const copy: Record<AssistantLocale, AssistantUICopy> = {
  en: {
    title: "Oriana Companion",
    subtitle: "Rule-based site helper",
    companionLabel: "Companion",
    greeting: "I can help with albums, private access, downloads, messages, and notifications.",
    privateAccess: "Private access",
    notifications: "Notifications",
    contactReplies: "Contact replies",
    siteRules: "Site rules",
    emptyState: "Ask in English or your selected site language. I only answer from website rules and safe account status.",
    handoffPrompt: "Send this question to Contact? Nothing is sent automatically; the Contact page will open with a draft.",
    openContactDraft: "Open Contact Draft",
    cancel: "Cancel",
    privacyNote: "This helper only uses website rules and your own account status.",
    inputPlaceholder: "Ask about access, ZIP, messages...",
    inputLabel: "Ask Oriana Companion",
    sendLabel: "Send question",
    closeLabel: "Close assistant",
    askDock: "Ask Oriana",
    hideDock: "Hide Oriana Companion for this session",
    contactHandoffTitle: "Contact handoff",
    unknownAnswer: "I'm not fully sure. You can send this to Oriana Wren through Contact.",
    emptyQuestionTitle: "Ask a website question",
    emptyQuestionAnswer: "Ask about albums, private access, downloads, messages, notifications, or account basics.",
    signIn: "Sign in",
    authRequiredAnswer: "Please sign in with Google first. After login, return to the album or page you were viewing and check your own request, message, or notification status there.",
    unreadNotification: (count) => ` You currently have ${count} unread notification${count === 1 ? "" : "s"}.`,
    openPath: (path) => `Open ${path.replace("/", "") || "home"}`,
    sendToContact: "Send to Contact",
  },
  vi: {
    title: "Oriana Companion",
    subtitle: "Trợ lý theo quy tắc của website",
    companionLabel: "Trợ lý",
    greeting: "Mình có thể giúp về album, quyền riêng tư, tải xuống, tin nhắn và thông báo.",
    privateAccess: "Quyền riêng tư",
    notifications: "Thông báo",
    contactReplies: "Phản hồi",
    siteRules: "Quy tắc",
    emptyState: "Hãy hỏi bằng tiếng Việt hoặc ngôn ngữ bạn đã chọn. Mình chỉ trả lời theo quy tắc website và trạng thái tài khoản an toàn.",
    handoffPrompt: "Gửi câu hỏi này sang Contact? Chưa có gì được gửi tự động; trang Contact sẽ mở kèm bản nháp.",
    openContactDraft: "Mở bản nháp Contact",
    cancel: "Hủy",
    privacyNote: "Trợ lý này chỉ dùng quy tắc website và trạng thái tài khoản của chính bạn.",
    inputPlaceholder: "Hỏi về quyền xem, ZIP, tin nhắn...",
    inputLabel: "Hỏi Oriana Companion",
    sendLabel: "Gửi câu hỏi",
    closeLabel: "Đóng trợ lý",
    askDock: "Hỏi Oriana",
    hideDock: "Ẩn Oriana Companion trong phiên này",
    contactHandoffTitle: "Chuyển sang Contact",
    unknownAnswer: "Mình chưa chắc chắn. Bạn có thể gửi câu hỏi này cho Oriana Wren qua Contact.",
    emptyQuestionTitle: "Hãy hỏi một câu về website",
    emptyQuestionAnswer: "Bạn có thể hỏi về album, quyền riêng tư, tải xuống, tin nhắn, thông báo hoặc tài khoản.",
    signIn: "Đăng nhập",
    authRequiredAnswer: "Vui lòng đăng nhập Google trước. Sau khi đăng nhập, quay lại album hoặc trang bạn đang xem để kiểm tra trạng thái yêu cầu, tin nhắn hoặc thông báo của chính bạn.",
    unreadNotification: (count) => ` Bạn hiện có ${count} thông báo chưa đọc.`,
    openPath: (path) => `Mở ${path.replace("/", "") || "trang chủ"}`,
    sendToContact: "Gửi sang Contact",
  },
  "zh-CN": {
    title: "Oriana Companion",
    subtitle: "网站规则助手",
    companionLabel: "助手",
    greeting: "我可以帮助你了解相册、私密访问、下载、消息和通知。",
    privateAccess: "私密访问",
    notifications: "通知",
    contactReplies: "联系回复",
    siteRules: "网站规则",
    emptyState: "请使用你选择的网站语言提问。我只根据网站规则和安全的账号状态回答。",
    handoffPrompt: "要把这个问题发到 Contact 吗？不会自动发送，只会打开带草稿的 Contact 页面。",
    openContactDraft: "打开 Contact 草稿",
    cancel: "取消",
    privacyNote: "此助手只使用网站规则和你自己的账号状态。",
    inputPlaceholder: "询问访问、ZIP、消息...",
    inputLabel: "询问 Oriana Companion",
    sendLabel: "发送问题",
    closeLabel: "关闭助手",
    askDock: "询问 Oriana",
    hideDock: "本次会话隐藏助手",
    contactHandoffTitle: "转到 Contact",
    unknownAnswer: "我不完全确定。你可以通过 Contact 将此问题发送给 Oriana Wren。",
    emptyQuestionTitle: "询问网站问题",
    emptyQuestionAnswer: "可以询问相册、私密访问、下载、消息、通知或账号基础问题。",
    signIn: "登录",
    authRequiredAnswer: "请先使用 Google 登录。登录后回到原来的相册或页面，查看你自己的请求、消息或通知状态。",
    unreadNotification: (count) => ` 你有 ${count} 条未读通知。`,
    openPath: (path) => `打开 ${path.replace("/", "") || "首页"}`,
    sendToContact: "发送到 Contact",
  },
  ja: {
    title: "Oriana Companion",
    subtitle: "サイトルール案内",
    companionLabel: "コンパニオン",
    greeting: "アルバム、非公開アクセス、ダウンロード、メッセージ、通知について案内できます。",
    privateAccess: "非公開アクセス",
    notifications: "通知",
    contactReplies: "返信",
    siteRules: "サイトルール",
    emptyState: "選択中のサイト言語で質問できます。回答はサイトルールと安全なアカウント状態に限定されます。",
    handoffPrompt: "この質問を Contact に送りますか？自動送信はせず、下書き付きで Contact ページを開きます。",
    openContactDraft: "Contact 下書きを開く",
    cancel: "キャンセル",
    privacyNote: "このヘルパーはサイトルールとあなた自身のアカウント状態だけを使います。",
    inputPlaceholder: "アクセス、ZIP、メッセージについて質問...",
    inputLabel: "Oriana Companion に質問",
    sendLabel: "質問を送信",
    closeLabel: "閉じる",
    askDock: "Oriana に質問",
    hideDock: "このセッションで非表示",
    contactHandoffTitle: "Contact へ引き継ぎ",
    unknownAnswer: "正確には分かりません。Contact から Oriana Wren に送ることができます。",
    emptyQuestionTitle: "サイトについて質問",
    emptyQuestionAnswer: "アルバム、非公開アクセス、ダウンロード、メッセージ、通知、アカウントについて質問できます。",
    signIn: "ログイン",
    authRequiredAnswer: "先に Google でログインしてください。ログイン後、見ていたアルバムやページに戻り、自分の申請、メッセージ、通知状態を確認してください。",
    unreadNotification: (count) => ` 未読通知が ${count} 件あります。`,
    openPath: (path) => `${path.replace("/", "") || "ホーム"}を開く`,
    sendToContact: "Contact に送る",
  },
  ko: {
    title: "Oriana Companion",
    subtitle: "사이트 규칙 도우미",
    companionLabel: "컴패니언",
    greeting: "앨범, 비공개 접근, 다운로드, 메시지, 알림을 도와드릴 수 있어요.",
    privateAccess: "비공개 접근",
    notifications: "알림",
    contactReplies: "답장",
    siteRules: "사이트 규칙",
    emptyState: "선택한 사이트 언어로 질문하세요. 사이트 규칙과 안전한 계정 상태만 기준으로 답합니다.",
    handoffPrompt: "이 질문을 Contact 로 보낼까요? 자동 전송은 없고 초안이 열린 Contact 페이지로 이동합니다.",
    openContactDraft: "Contact 초안 열기",
    cancel: "취소",
    privacyNote: "이 도우미는 사이트 규칙과 본인 계정 상태만 사용합니다.",
    inputPlaceholder: "접근, ZIP, 메시지 질문...",
    inputLabel: "Oriana Companion 에 질문",
    sendLabel: "질문 보내기",
    closeLabel: "도우미 닫기",
    askDock: "Oriana 에 질문",
    hideDock: "이 세션에서 숨기기",
    contactHandoffTitle: "Contact 로 전달",
    unknownAnswer: "정확히 확신할 수 없습니다. Contact 를 통해 Oriana Wren 에게 보낼 수 있습니다.",
    emptyQuestionTitle: "사이트 질문하기",
    emptyQuestionAnswer: "앨범, 비공개 접근, 다운로드, 메시지, 알림 또는 계정 기본 사항을 질문하세요.",
    signIn: "로그인",
    authRequiredAnswer: "먼저 Google 로 로그인하세요. 로그인 후 보던 앨범이나 페이지로 돌아가 본인의 요청, 메시지, 알림 상태를 확인하세요.",
    unreadNotification: (count) => ` 읽지 않은 알림이 ${count}개 있습니다.`,
    openPath: (path) => `${path.replace("/", "") || "홈"} 열기`,
    sendToContact: "Contact 로 보내기",
  },
  th: {
    title: "Oriana Companion",
    subtitle: "ผู้ช่วยตามกฎของเว็บไซต์",
    companionLabel: "ผู้ช่วย",
    greeting: "ฉันช่วยเรื่องอัลบั้ม สิทธิ์ส่วนตัว ดาวน์โหลด ข้อความ และการแจ้งเตือนได้",
    privateAccess: "สิทธิ์ส่วนตัว",
    notifications: "การแจ้งเตือน",
    contactReplies: "คำตอบ",
    siteRules: "กฎเว็บไซต์",
    emptyState: "ถามด้วยภาษาที่เลือกไว้ได้ ฉันตอบจากกฎเว็บไซต์และสถานะบัญชีที่ปลอดภัยเท่านั้น",
    handoffPrompt: "ส่งคำถามนี้ไปที่ Contact ไหม? ยังไม่ส่งอัตโนมัติ แต่จะเปิดหน้า Contact พร้อมแบบร่าง",
    openContactDraft: "เปิดแบบร่าง Contact",
    cancel: "ยกเลิก",
    privacyNote: "ผู้ช่วยนี้ใช้เฉพาะกฎเว็บไซต์และสถานะบัญชีของคุณเอง",
    inputPlaceholder: "ถามเรื่องสิทธิ์ ZIP ข้อความ...",
    inputLabel: "ถาม Oriana Companion",
    sendLabel: "ส่งคำถาม",
    closeLabel: "ปิดผู้ช่วย",
    askDock: "ถาม Oriana",
    hideDock: "ซ่อนในเซสชันนี้",
    contactHandoffTitle: "ส่งต่อไป Contact",
    unknownAnswer: "ฉันยังไม่แน่ใจ คุณสามารถส่งคำถามนี้ถึง Oriana Wren ผ่าน Contact ได้",
    emptyQuestionTitle: "ถามเกี่ยวกับเว็บไซต์",
    emptyQuestionAnswer: "ถามเรื่องอัลบั้ม สิทธิ์ส่วนตัว ดาวน์โหลด ข้อความ การแจ้งเตือน หรือบัญชีได้",
    signIn: "เข้าสู่ระบบ",
    authRequiredAnswer: "โปรดเข้าสู่ระบบด้วย Google ก่อน จากนั้นกลับไปยังอัลบั้มหรือหน้าที่ดูอยู่เพื่อตรวจสอบคำขอ ข้อความ หรือการแจ้งเตือนของคุณ",
    unreadNotification: (count) => ` คุณมีการแจ้งเตือนที่ยังไม่ได้อ่าน ${count} รายการ`,
    openPath: (path) => `เปิด ${path.replace("/", "") || "หน้าแรก"}`,
    sendToContact: "ส่งไป Contact",
  },
  id: {
    title: "Oriana Companion",
    subtitle: "Asisten aturan situs",
    companionLabel: "Asisten",
    greeting: "Saya bisa membantu soal album, akses privat, unduhan, pesan, dan notifikasi.",
    privateAccess: "Akses privat",
    notifications: "Notifikasi",
    contactReplies: "Balasan",
    siteRules: "Aturan situs",
    emptyState: "Tanyakan dalam bahasa situs yang dipilih. Saya hanya menjawab dari aturan situs dan status akun yang aman.",
    handoffPrompt: "Kirim pertanyaan ini ke Contact? Tidak ada yang dikirim otomatis; halaman Contact akan terbuka dengan draf.",
    openContactDraft: "Buka draf Contact",
    cancel: "Batal",
    privacyNote: "Asisten ini hanya memakai aturan situs dan status akun Anda sendiri.",
    inputPlaceholder: "Tanya akses, ZIP, pesan...",
    inputLabel: "Tanya Oriana Companion",
    sendLabel: "Kirim pertanyaan",
    closeLabel: "Tutup asisten",
    askDock: "Tanya Oriana",
    hideDock: "Sembunyikan untuk sesi ini",
    contactHandoffTitle: "Alihkan ke Contact",
    unknownAnswer: "Saya belum yakin. Anda bisa mengirim pertanyaan ini ke Oriana Wren lewat Contact.",
    emptyQuestionTitle: "Tanyakan soal situs",
    emptyQuestionAnswer: "Tanyakan soal album, akses privat, unduhan, pesan, notifikasi, atau dasar akun.",
    signIn: "Masuk",
    authRequiredAnswer: "Silakan masuk dengan Google terlebih dahulu. Setelah masuk, kembali ke album atau halaman yang Anda buka untuk memeriksa status permintaan, pesan, atau notifikasi Anda sendiri.",
    unreadNotification: (count) => ` Anda memiliki ${count} notifikasi belum dibaca.`,
    openPath: (path) => `Buka ${path.replace("/", "") || "beranda"}`,
    sendToContact: "Kirim ke Contact",
  },
  fr: {
    title: "Oriana Companion",
    subtitle: "Assistant des règles du site",
    companionLabel: "Assistant",
    greeting: "Je peux aider pour les albums, l'accès privé, les téléchargements, les messages et les notifications.",
    privateAccess: "Accès privé",
    notifications: "Notifications",
    contactReplies: "Réponses",
    siteRules: "Règles du site",
    emptyState: "Posez une question dans la langue choisie. Je réponds seulement avec les règles du site et l'état sûr du compte.",
    handoffPrompt: "Envoyer cette question à Contact ? Rien n'est envoyé automatiquement; une page Contact avec brouillon s'ouvrira.",
    openContactDraft: "Ouvrir le brouillon",
    cancel: "Annuler",
    privacyNote: "Cet assistant utilise seulement les règles du site et l'état de votre propre compte.",
    inputPlaceholder: "Question sur accès, ZIP, messages...",
    inputLabel: "Demander à Oriana Companion",
    sendLabel: "Envoyer la question",
    closeLabel: "Fermer l'assistant",
    askDock: "Demander à Oriana",
    hideDock: "Masquer pour cette session",
    contactHandoffTitle: "Transfert vers Contact",
    unknownAnswer: "Je ne suis pas totalement sûr. Vous pouvez envoyer cette question à Oriana Wren via Contact.",
    emptyQuestionTitle: "Posez une question sur le site",
    emptyQuestionAnswer: "Demandez au sujet des albums, accès privés, téléchargements, messages, notifications ou bases du compte.",
    signIn: "Se connecter",
    authRequiredAnswer: "Veuillez d'abord vous connecter avec Google. Après connexion, revenez à l'album ou à la page consultée pour vérifier vos demandes, messages ou notifications.",
    unreadNotification: (count) => ` Vous avez ${count} notification(s) non lue(s).`,
    openPath: (path) => `Ouvrir ${path.replace("/", "") || "accueil"}`,
    sendToContact: "Envoyer à Contact",
  },
  de: {
    title: "Oriana Companion",
    subtitle: "Regelbasierte Website-Hilfe",
    companionLabel: "Begleiter",
    greeting: "Ich helfe bei Alben, privatem Zugriff, Downloads, Nachrichten und Benachrichtigungen.",
    privateAccess: "Privater Zugriff",
    notifications: "Benachrichtigungen",
    contactReplies: "Antworten",
    siteRules: "Website-Regeln",
    emptyState: "Fragen Sie in der gewählten Website-Sprache. Ich antworte nur anhand der Website-Regeln und sicherer Kontodaten.",
    handoffPrompt: "Diese Frage an Contact senden? Es wird nichts automatisch gesendet; Contact öffnet sich mit einem Entwurf.",
    openContactDraft: "Contact-Entwurf öffnen",
    cancel: "Abbrechen",
    privacyNote: "Diese Hilfe nutzt nur Website-Regeln und den Status Ihres eigenen Kontos.",
    inputPlaceholder: "Frage zu Zugriff, ZIP, Nachrichten...",
    inputLabel: "Oriana Companion fragen",
    sendLabel: "Frage senden",
    closeLabel: "Assistent schließen",
    askDock: "Oriana fragen",
    hideDock: "Für diese Sitzung ausblenden",
    contactHandoffTitle: "An Contact übergeben",
    unknownAnswer: "Ich bin nicht ganz sicher. Sie können diese Frage über Contact an Oriana Wren senden.",
    emptyQuestionTitle: "Website-Frage stellen",
    emptyQuestionAnswer: "Fragen Sie zu Alben, privatem Zugriff, Downloads, Nachrichten, Benachrichtigungen oder Konto-Grundlagen.",
    signIn: "Anmelden",
    authRequiredAnswer: "Bitte melden Sie sich zuerst mit Google an. Kehren Sie danach zum Album oder zur Seite zurück und prüfen Sie dort Ihre eigenen Anfragen, Nachrichten oder Benachrichtigungen.",
    unreadNotification: (count) => ` Sie haben ${count} ungelesene Benachrichtigung(en).`,
    openPath: (path) => `${path.replace("/", "") || "Startseite"} öffnen`,
    sendToContact: "An Contact senden",
  },
  es: {
    title: "Oriana Companion",
    subtitle: "Ayuda basada en reglas del sitio",
    companionLabel: "Asistente",
    greeting: "Puedo ayudar con álbumes, acceso privado, descargas, mensajes y notificaciones.",
    privateAccess: "Acceso privado",
    notifications: "Notificaciones",
    contactReplies: "Respuestas",
    siteRules: "Reglas del sitio",
    emptyState: "Pregunta en el idioma elegido del sitio. Solo respondo con reglas del sitio y estado seguro de tu cuenta.",
    handoffPrompt: "¿Enviar esta pregunta a Contact? No se envía nada automáticamente; se abrirá Contact con un borrador.",
    openContactDraft: "Abrir borrador de Contact",
    cancel: "Cancelar",
    privacyNote: "Este asistente solo usa reglas del sitio y el estado de tu propia cuenta.",
    inputPlaceholder: "Pregunta sobre acceso, ZIP, mensajes...",
    inputLabel: "Preguntar a Oriana Companion",
    sendLabel: "Enviar pregunta",
    closeLabel: "Cerrar asistente",
    askDock: "Preguntar a Oriana",
    hideDock: "Ocultar en esta sesión",
    contactHandoffTitle: "Enviar a Contact",
    unknownAnswer: "No estoy totalmente seguro. Puedes enviar esto a Oriana Wren mediante Contact.",
    emptyQuestionTitle: "Haz una pregunta del sitio",
    emptyQuestionAnswer: "Pregunta sobre álbumes, acceso privado, descargas, mensajes, notificaciones o cuenta.",
    signIn: "Iniciar sesión",
    authRequiredAnswer: "Primero inicia sesión con Google. Después vuelve al álbum o página que estabas viendo y revisa allí tu solicitud, mensaje o notificación.",
    unreadNotification: (count) => ` Tienes ${count} notificación(es) sin leer.`,
    openPath: (path) => `Abrir ${path.replace("/", "") || "inicio"}`,
    sendToContact: "Enviar a Contact",
  },
};

export function getAssistantUICopy(locale: unknown): AssistantUICopy {
  const safeLocale = normalizeAssistantLocale(locale);
  return copy[safeLocale] ?? copy[DEFAULT_ASSISTANT_LOCALE];
}
