import type { AlbumDetail } from "@/lib/types";

const now = new Date("2026-07-06T09:00:00.000Z").toISOString();

export const sampleAlbums: AlbumDetail[] = [
  {
    id: "summer-vacation",
    title: "Summer Vacation",
    slug: "summer-vacation",
    description: "Golden coastlines, slow mornings, and family snapshots.",
    cover_image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85",
    is_public: true,
    photo_count: 8,
    created_at: now,
    updated_at: now,
    images: [
      {
        id: "sv-1",
        album_id: "summer-vacation",
        file_name: "shoreline.jpg",
        width: 1200,
        height: 1600,
        file_size: null,
        content_type: "image/jpeg",
        blur_hash: "LEHV6nWB2yk8pyo0adR*.7kCMdnj",
        original_key: null,
        medium_key: null,
        thumb_key: null,
        file_url:
          "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=85",
        created_at: now,
        is_favorite: true,
      },
      {
        id: "sv-2",
        album_id: "summer-vacation",
        file_name: "cliff-walk.jpg",
        width: 1200,
        height: 900,
        file_size: null,
        content_type: "image/jpeg",
        blur_hash: "LqPj0^E1M|s:xuM{RjoL?aWBayj[",
        original_key: null,
        medium_key: null,
        thumb_key: null,
        file_url:
          "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=85",
        created_at: now,
      },
      {
        id: "sv-3",
        album_id: "summer-vacation",
        file_name: "poolside.jpg",
        width: 1200,
        height: 1500,
        file_size: null,
        content_type: "image/jpeg",
        blur_hash: "LJL|2{?b9aM|_N%MRjayIVWB%1WB",
        original_key: null,
        medium_key: null,
        thumb_key: null,
        file_url:
          "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1200&q=85",
        created_at: now,
      },
      {
        id: "sv-4",
        album_id: "summer-vacation",
        file_name: "blue-hour.jpg",
        width: 1200,
        height: 800,
        file_size: null,
        content_type: "image/jpeg",
        blur_hash: "L8E:DS02M{_3%LRjM{M{00of%MRj",
        original_key: null,
        medium_key: null,
        thumb_key: null,
        file_url:
          "https://images.unsplash.com/photo-1473116763249-2faaef81ccda?auto=format&fit=crop&w=1200&q=85",
        created_at: now,
      },
      {
        id: "sv-5",
        album_id: "summer-vacation",
        file_name: "sunset-boardwalk.jpg",
        width: 1200,
        height: 1800,
        file_size: null,
        content_type: "image/jpeg",
        blur_hash: "LHG8s?xuxuW;~qofj[WBx]oLWBay",
        original_key: null,
        medium_key: null,
        thumb_key: null,
        file_url:
          "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85",
        created_at: now,
      },
      {
        id: "sv-6",
        album_id: "summer-vacation",
        file_name: "cafe-table.jpg",
        width: 1200,
        height: 900,
        file_size: null,
        content_type: "image/jpeg",
        blur_hash: "LRKe]D%2IoRj~qofRjayxuf6RjWB",
        original_key: null,
        medium_key: null,
        thumb_key: null,
        file_url:
          "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85",
        created_at: now,
      },
      {
        id: "sv-7",
        album_id: "summer-vacation",
        file_name: "morning-swim.jpg",
        width: 1200,
        height: 1500,
        file_size: null,
        content_type: "image/jpeg",
        blur_hash: "L5GkW^0000?wE1j]t7of00^+~qRj",
        original_key: null,
        medium_key: null,
        thumb_key: null,
        file_url:
          "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=85",
        created_at: now,
      },
      {
        id: "sv-8",
        album_id: "summer-vacation",
        file_name: "open-road.jpg",
        width: 1200,
        height: 800,
        file_size: null,
        content_type: "image/jpeg",
        blur_hash: "LBI#]R?b?bRj_M%MWBay%M-;Rjxu",
        original_key: null,
        medium_key: null,
        thumb_key: null,
        file_url:
          "https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=1200&q=85",
        created_at: now,
      },
    ],
  },
  {
    id: "city-lights",
    title: "City Lights",
    slug: "city-lights",
    description: "A clean edit of late-night streets and reflective glass.",
    cover_image:
      "https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=85",
    is_public: true,
    photo_count: 24,
    created_at: now,
    updated_at: now,
    images: [],
  },
  {
    id: "quiet-studio",
    title: "Quiet Studio",
    slug: "quiet-studio",
    description: "Still-life references and soft product tests.",
    cover_image:
      "https://images.unsplash.com/photo-1518005020951-eccb494ad742?auto=format&fit=crop&w=1200&q=85",
    is_public: false,
    photo_count: 16,
    created_at: now,
    updated_at: now,
    images: [],
  },
];
