import type { GameCatalogEntry } from "./core/types.ts";

export const gameCatalog = [
  {
    id: "00000000-0000-4000-8000-000000000010",
    slug: "snake",
    title: "Wren Trail Snake",
    description: "Guide a ribbon-tailed wren through a quiet moonlit garden.",
    engineKey: "snake-v1",
    version: "1.0.0",
    category: "arcade",
    accent: "sage",
    status: "published",
    rewardMode: "verified",
    legacy: false,
    enabled: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000020",
    slug: "feather-merge",
    title: "Feather Merge",
    description: "Compose matching feathers into an increasingly luminous collection.",
    engineKey: "feather-merge-v1",
    version: "1.0.0",
    category: "logic",
    accent: "amber",
    status: "published",
    rewardMode: "verified",
    legacy: false,
    enabled: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000030",
    slug: "memory-garden",
    title: "Memory Garden",
    description: "Reveal and pair botanical keepsakes from Oriana's seasonal garden.",
    engineKey: "memory-garden-v1",
    version: "1.0.0",
    category: "logic",
    accent: "rose",
    status: "published",
    rewardMode: "verified",
    legacy: false,
    enabled: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000040",
    slug: "quiet-meadow",
    title: "Quiet Meadow",
    description: "Carefully uncover the hidden blooms and dew across the peaceful meadow.",
    engineKey: "quiet-meadow-v1",
    version: "1.0.0",
    category: "logic",
    accent: "sage",
    status: "published",
    rewardMode: "verified",
    legacy: false,
    enabled: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000050",
    slug: "echo-chimes",
    title: "Echo Chimes",
    description: "Listen to the wind chimes and repeat their delicate melody.",
    engineKey: "echo-chimes-v1",
    version: "1.0.0",
    category: "logic",
    accent: "sky",
    status: "published",
    rewardMode: "verified",
    legacy: false,
    enabled: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000060",
    slug: "wren-flight",
    title: "Wren Flight",
    description: "Guide the ribbon-tailed wren safely through the hanging vines.",
    engineKey: "wren-flight-v1",
    version: "1.0.0",
    category: "arcade",
    accent: "amber",
    status: "published",
    rewardMode: "verified",
    legacy: false,
    enabled: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000070",
    slug: "zen-cairn",
    title: "Zen Cairn",
    description: "Stack smooth river stones perfectly to build a towering cairn.",
    engineKey: "zen-cairn-v1",
    version: "1.0.0",
    category: "arcade",
    accent: "rose",
    status: "published",
    rewardMode: "verified",
    legacy: false,
    enabled: true,
  },
  {
    id: "00000000-0000-4000-8000-000000000001",
    slug: "puzzle-atelier",
    title: "Puzzle Atelier",
    description: "Oriana Wren's existing editorial sliding and swap puzzle.",
    engineKey: "legacy-puzzle-atelier",
    version: "legacy-1",
    category: "atelier",
    accent: "sky",
    status: "published",
    rewardMode: "verified",
    legacy: true,
    enabled: true,
  },
] as const satisfies readonly GameCatalogEntry[];

export const publishedGameCatalog = gameCatalog.filter(
  (entry) => entry.enabled && entry.status === "published",
);

export function getGameCatalogEntry(slug: string) {
  return gameCatalog.find((entry) => entry.slug === slug) ?? null;
}
